version: "3.6"
services:
  # https://hub.docker.com/_/nginx
  nginx:
    image: geekyouth/nginx-amplify:1.19.0.1
    hostname: nginx-amplify
    container_name: nginx-amplify
    depends_on:
      - cluster01
      - cluster02
      - cluster03
    volumes:
      # - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      NGINX_PORT: 80
      API_KEY: 0451f483e67e42d7db7644554ca48e08 # 自己申请 https://amplify.nginx.com/
      AMPLIFY_IMAGENAME: docker-nginx-sz
    networks:
      - elastic

  # https://www.elastic.co/guide/en/elastic-stack-get-started/7.9/get-started-docker.html
  cluster01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    hostname: cluster01
    container_name: cluster01
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      discovery.type: single-node
      node.name: es01
      cluster.name: cluster01
      discovery.seed_hosts: es01
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic

  cluster02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    hostname: cluster02
    container_name: cluster02
    ports:
      - "9202:9200"
      - "9302:9300"
    environment:
      discovery.type: single-node
      node.name: es02
      cluster.name: cluster02
      discovery.seed_hosts: es02
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic

  cluster03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    hostname: cluster03
    container_name: cluster03
    ports:
      - "9203:9200"
      - "9303:9300"
    environment:
      discovery.type: single-node
      node.name: es03
      cluster.name: cluster03
      discovery.seed_hosts: es03
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic

networks:
  elastic:
    driver: bridge

# docker-compose -f nginx-es-compose.yaml up -d
# docker-compose -f nginx-es-compose.yaml down

# git clone -c http.proxy="http://lx:10800" https://github.com/geekyouth/docker-nginx-amplify
